extends RefCounted

const IDLE_FRAMES := [
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0081.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0082.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0083.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0084.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0085.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0086.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0087.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0088.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0089.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0090.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0091.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0092.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0093.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0094.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0095.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0096.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0097.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0098.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0099.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0100.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0101.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0102.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0103.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0104.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0105.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0106.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0107.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0108.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0109.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0110.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0111.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0112.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0113.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0114.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0115.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0116.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0117.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0118.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/idle/actions0119.png"),
]

const WALK_FRAMES := [
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0001.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0002.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0003.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0004.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0005.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0006.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0007.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0008.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0009.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0010.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0011.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0012.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0013.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0014.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0015.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0016.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0017.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0018.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0019.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0020.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0021.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0022.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0023.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0024.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0025.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0026.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0027.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0028.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0029.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0030.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0031.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0032.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0033.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0034.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0035.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0036.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0037.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0038.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0039.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0040.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0041.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0042.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0043.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0044.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0045.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0046.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0047.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0048.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0049.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0050.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0051.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0052.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0053.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0054.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0055.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0056.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0057.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0058.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0059.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0060.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0061.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0062.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0063.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0064.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0065.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0066.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0067.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0068.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0069.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0070.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0071.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0072.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0073.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0074.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0075.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0076.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0077.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0078.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0079.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/walk/actions0080.png"),
]

const ATTACK_FRAMES := [
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0287.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0288.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0289.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0290.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0291.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0292.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0293.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0294.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0295.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0296.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0297.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0298.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0299.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0300.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0301.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0302.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0303.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0304.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0305.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0306.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/attack02/actions0307.png"),
]

const HURT_FRAMES := [
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0140.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0141.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0142.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0143.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0144.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0145.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0146.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0147.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0148.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0149.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0150.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0151.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0152.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0153.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0154.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0155.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0156.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0157.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0158.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0159.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/high damage/actions0160.png"),
]

const DEATH_FRAMES := [
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0174.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0175.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0176.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0177.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0178.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0179.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0180.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0181.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0182.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0183.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0184.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0185.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0186.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0187.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0188.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0189.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0190.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0191.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0192.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0193.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0194.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0195.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0196.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0197.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0198.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0199.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0200.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0201.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0202.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0203.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0204.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0205.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0206.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0207.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0208.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0209.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0210.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0211.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0212.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0213.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0214.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0215.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0216.png"),
	preload("res://assets/sprites/spider boss/Spider Actions/death/actions0217.png"),
]

